version: '3'
services:
  web:
    build: .
    restart: always
    container_name: message-receiver
    ports:
    - 8080:8080
    environment:
    - "SPRING_PROFILES_ACTIVE=default"
    networks:
    - spring
  redis:
    image: redis:latest
    command: [ "redis-server", "--protected-mode", "no" ]
    ports:
    - 6379:6379
    networks:
    - spring
  
networks:
  spring:
    external: true